ostree: Move dpkg database into /usr
Once the OS /var gets mounted over the deployment /var at runtime, the
dpkg database is no longer accessible. This makes both dpkg and apt
useless as they don't know the system state.

Move the dpkg database into /usr/share/dpkg so that it can be seen at
runtime. A symlink in the deployment and tmpfiles.d configuration are
added so that a the tools will see the data unmodified. The symlink in
the deployment is just to help when inspecting a checkout without
booting it.

This is the same concept as rpm-ostree, which moves the rpm database
from /var/lib/rpm to /usr/share/rpm.

https://phabricator.endlessm.com/T14382

diff --git a/stages/eob_ostree b/stages/eob_ostree
--- a/stages/eob_ostree
+++ b/stages/eob_ostree
@@ -115,12 +115,26 @@ cat <<EOF > "${EOB_ROOTDIR}"/usr/etc/fstab
 LABEL=ostree / ext4  errors=remount-ro 0 0
 EOF
 
+# Move dpkg database to /usr so it's accessible after the OS /var is
+# mounted, but make a symlink so it works without modifications to dpkg
+# or apt
+mkdir -p "${EOB_ROOTDIR}"/usr/share/dpkg
+if [ -e "${EOB_ROOTDIR}"/usr/share/dpkg/database ]; then
+  echo "ERROR: /usr/share/dpkg/database already exists!" >&2
+  ls -lR "${EOB_ROOTDIR}"/usr/share/dpkg/database >&2
+  exit 1
+fi
+mv "${EOB_ROOTDIR}"/var/lib/dpkg "${EOB_ROOTDIR}"/usr/share/dpkg/database
+ln -srv "${EOB_ROOTDIR}"/usr/share/dpkg/database \
+   "${EOB_ROOTDIR}"/var/lib/dpkg
+
 cat <<EOF > "${EOB_ROOTDIR}"/usr/lib/tmpfiles.d/ostree.conf
 L /var/home - - - - ../sysroot/home
 d /var/roothome 0700 root root -
 d /var/opt 0755 root root -
 d /var/local 0755 root root -
 d /run/media 0755 root root -
+L /var/lib/dpkg - - - - ../../usr/share/dpkg/database
 EOF
 
 mkdir -p "${EOB_ROOTDIR}"/sysroot
